///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace CopyLine
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the CopyLineRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    [RepositoryFolder("f0eebc5f-379c-4061-a4dc-1b9b66953d4b")]
    public partial class CopyLineRepository : RepoGenBaseFolder
    {
        static CopyLineRepository instance = new CopyLineRepository();
        CopyLineRepositoryFolders.MeasureXUntitledAppFolder _measurexuntitled;
        CopyLineRepositoryFolders.InspectionAppFolder _inspection;

        /// <summary>
        /// Gets the singleton class instance representing the CopyLineRepository element repository.
        /// </summary>
        [RepositoryFolder("f0eebc5f-379c-4061-a4dc-1b9b66953d4b")]
        public static CopyLineRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public CopyLineRepository() 
            : base("CopyLineRepository", "/", null, 0, false, "f0eebc5f-379c-4061-a4dc-1b9b66953d4b", ".\\RepositoryImages\\CopyLineRepositoryf0eebc5f.rximgres")
        {
            _measurexuntitled = new CopyLineRepositoryFolders.MeasureXUntitledAppFolder(this);
            _inspection = new CopyLineRepositoryFolders.InspectionAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f0eebc5f-379c-4061-a4dc-1b9b66953d4b")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The MeasureXUntitled folder.
        /// </summary>
        [RepositoryFolder("6ccbc959-460e-4d50-8f44-2f0d5ad8e6e4")]
        public virtual CopyLineRepositoryFolders.MeasureXUntitledAppFolder MeasureXUntitled
        {
            get { return _measurexuntitled; }
        }

        /// <summary>
        /// The Inspection folder.
        /// </summary>
        [RepositoryFolder("2b0a2f72-b3d2-46e7-b4b3-779da1802eff")]
        public virtual CopyLineRepositoryFolders.InspectionAppFolder Inspection
        {
            get { return _inspection; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    public partial class CopyLineRepositoryFolders
    {
        /// <summary>
        /// The MeasureXUntitledAppFolder folder.
        /// </summary>
        [RepositoryFolder("6ccbc959-460e-4d50-8f44-2f0d5ad8e6e4")]
        public partial class MeasureXUntitledAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _measurexuntitledInfo;

            /// <summary>
            /// Creates a new MeasureXUntitled  folder.
            /// </summary>
            public MeasureXUntitledAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MeasureXUntitled", "/form[@title='Measure-X - [Untitled]']", parentFolder, 30000, null, true, "6ccbc959-460e-4d50-8f44-2f0d5ad8e6e4", "")
            {
                _measurexuntitledInfo = new RepoItemInfo(this, "MeasureXUntitled", "titlebar[@accessiblerole='TitleBar']", 120000, null, "50c8024c-01bf-4795-976b-4cb77ef73407");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6ccbc959-460e-4d50-8f44-2f0d5ad8e6e4")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6ccbc959-460e-4d50-8f44-2f0d5ad8e6e4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MeasureXUntitled item.
            /// </summary>
            [RepositoryItem("50c8024c-01bf-4795-976b-4cb77ef73407")]
            public virtual Ranorex.TitleBar MeasureXUntitled
            {
                get
                {
                    return _measurexuntitledInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The MeasureXUntitled item info.
            /// </summary>
            [RepositoryItemInfo("50c8024c-01bf-4795-976b-4cb77ef73407")]
            public virtual RepoItemInfo MeasureXUntitledInfo
            {
                get
                {
                    return _measurexuntitledInfo;
                }
            }
        }

        /// <summary>
        /// The InspectionAppFolder folder.
        /// </summary>
        [RepositoryFolder("2b0a2f72-b3d2-46e7-b4b3-779da1802eff")]
        public partial class InspectionAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _afterrunbuttonokInfo;

            /// <summary>
            /// Creates a new Inspection  folder.
            /// </summary>
            public InspectionAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Inspection", "/form[@title='Inspection']", parentFolder, 30000, null, true, "2b0a2f72-b3d2-46e7-b4b3-779da1802eff", "")
            {
                _afterrunbuttonokInfo = new RepoItemInfo(this, "AfterRunButtonOK", "button[@text='&OK']", 120000, null, "23a02184-05ce-4263-a821-0146b038f4ea");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2b0a2f72-b3d2-46e7-b4b3-779da1802eff")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2b0a2f72-b3d2-46e7-b4b3-779da1802eff")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AfterRunButtonOK item.
            /// </summary>
            [RepositoryItem("23a02184-05ce-4263-a821-0146b038f4ea")]
            public virtual Ranorex.Button AfterRunButtonOK
            {
                get
                {
                    return _afterrunbuttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AfterRunButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("23a02184-05ce-4263-a821-0146b038f4ea")]
            public virtual RepoItemInfo AfterRunButtonOKInfo
            {
                get
                {
                    return _afterrunbuttonokInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}